# Generated by Django 5.0.2 on 2024-02-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audiorecording_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecording',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='spectrogram_uploads/'),
        ),
    ]
